version: '3'
services:
  sw-elasticsearch:
       image: eks17:1
       ports:
         - 9200:9200

  sw-postgres:
       image: pg17:2
       ports:
              - 5432:5432
       environment:
              - HOST=172.17.0.1/24 
  sw-couchbase:
       image: couch17:1
       ports:
            - 8091-8096:8091-8096
  sw-nginx:
      image: ng17:1
      ports:
           - 80:80
      environment:
          - HOST_IP=172.17.0.1

  sw-app:
       image: railsapp:v0.1.1    
       ports:
            - 3000:3000
       volumes:
             - /home/suroor/sw-deploy-r2r-/deploy/setup_dir/:/shared

       depends_on:
            - "postgres"

