version: '3'
services:
  sw-elasticsearch:
    image: prathambooksdocker/eks17:1
    ports:
      - 9200:9200
    networks:
      - sw-network

  sw-postgres:
    image: prathambooksdocker/pg17:2
    ports:
      - 5432:5432
    environment:
      - HOST=sw-app
    networks:
      - sw-network

  sw-couchbase:
    image: prathambooksdocker/couch17:1
    ports:
      - 8091-8096:8091-8096
    networks:
      - sw-network

  sw-nginx:
    image: prathambooksdocker/ng17:1
    ports:
      - 80:80
    environment:
      - HOST_IP=192.168.1.109
    networks:
      - sw-network
    depends_on:
      - "sw-app"

  sw-app:
    image: prathambooksdocker/railsapp:v0.1.1
    ports:
      - 3000:3000
    volumes:
      - /home/suroor/sw-deploy-r2r-/deploy/setup_dir/:/shared
    networks:
      - sw-network
    depends_on:
      - "sw-postgres"
      - "sw-elasticsearch"
      - "sw-couchbase"

networks:
  sw-network:
    driver: overlay
